server.port: 18080

settings:
  schema-registry: http://127.0.0.1:8081
  kafka-brokers: localhost:9092

spring.cloud.stream:

  function.definition: topologyA;topologyR;topologyB

  kafka.streams:
    binder:
      auto-create-topics: true
      brokers: ${settings.kafka-brokers}

      configuration:
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

      functions:
        topologyA.applicationId: topologyA
        topologyB.applicationId: topologyB

  kafka:
    binder:
      brokers: ${settings.kafka-brokers}

      producer-properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
#        value.serializer: org.apache.kafka.common.serialization.StringSerializer

      consumer-properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

  bindings:

    topologyA-in-0:
      destination: topic1
    topologyA-out-0:
      destination: topic2

    topologyR-in-0:
      group: topologyR
      destination: topic2
    topologyR-out-0:
      destination: topic3
      producer:
        useNativeEncoding: true

    topologyB-in-0:
      destination: topic3
